### ISSUE TITLE
Panic: index out of range

### ISSUE THREAD

**Issue by kshamajain99** [argoproj-labs/argocd-notifications#171]
argocd-notifications controller panicked because of following error

```
Recovered from panic: runtime error: index out of range [1] with length 1\
goroutine 1170056 [running]:\
runtime/debug.Stack(0xc0010f10b0, 0x1dd0320, 0xc0007587a0)\
\\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9f\
github.com/argoproj-labs/argocd-notifications/controller.(*notificationController).processQueueItem.func1(0xc0005fb200, 0x1be97c0, 0xc000dc2c30)\
\\t/src/controller/controller.go:320 +0x88\
panic(0x1dd0320, 0xc0007587a0)\
\\t/usr/local/go/src/runtime/panic.go:969 +0x1b9\
github.com/argoproj-labs/argocd-notifications/pkg/subscriptions.Annotations.iterate(0xc000b6ac30, 0xc0010f13c0)\
\\t/src/pkg/subscriptions/annotations.go:42 +0x293\
github.com/argoproj-labs/argocd-notifications/pkg/subscriptions.Annotations.GetAll(0xc000b6ac30, 0x0, 0x0, 0x0, 0xc000b6ac30)\
\\t/src/pkg/subscriptions/annotations.go:110 +0x8c\
github.com/argoproj-labs/argocd-notifications/controller.(*notificationController).getSubscriptions(0xc0005fb200, 0xc00081c038, 0xc000b6a9f0)\
\\t/src/controller/controller.go:254 +0x1c5\
github.com/argoproj-labs/argocd-notifications/controller.(*notificationController).processApp(0xc0005fb200, 0xc00081c038, 0xc0005642a0, 0x1, 0x1)\
\\t/src/controller/controller.go:171 +0x19c\
github.com/argoproj-labs/argocd-notifications/controller.(*notificationController).processQueueItem(0xc0005fb200, 0x203001)\
\\t/src/controller/controller.go:346 +0x451\
github.com/argoproj-labs/argocd-notifications/controller.(*notificationController).Run.func1()\
\\t/src/controller/controller.go:133 +0x36\
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00062e620)\
\\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155 +0x5f\
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00062e620, 0x2161a40, 0xc000926210, 0x1be9701, 0xc001118c60)\
\\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156 +0xad\
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00062e620, 0x3b9aca00, 0x0, 0x1, 0xc001118c60)\
\\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133 +0x98\
k8s.io/apimachinery/pkg/util/wait.Until(0xc00062e620, 0x3b9aca00, 0xc001118c60)\
\\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:90 +0x4d\
created by github.com/argoproj-labs/argocd-notifications/controller.(*notificationController).Run\
\\t/src/controller/controller.go:132 +0x119\
"
```

**Comment by kshamajain99** [comment]
fixed by https://github.com/argoproj-labs/argocd-notifications/pull/159
